// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj6yQevvbXCY5Rdblu5zPMcCRFfzna7tU',
    appId: '1:589729199634:web:8c4bfc471969bde0d08acb',
    messagingSenderId: '589729199634',
    projectId: 'tengkulakuapp',
    authDomain: 'tengkulakuapp.firebaseapp.com',
    storageBucket: 'tengkulakuapp.appspot.com',
    measurementId: 'G-TKSS2X7865',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhFAxVHC-8ttqq_RqDYUGEMR1164kv_Ac',
    appId: '1:589729199634:android:9fb6ec9c9ee2561ad08acb',
    messagingSenderId: '589729199634',
    projectId: 'tengkulakuapp',
    storageBucket: 'tengkulakuapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ohUxvduWEXx0ln6QJmZVxpGAh27mM50',
    appId: '1:589729199634:ios:a80d36a346228c64d08acb',
    messagingSenderId: '589729199634',
    projectId: 'tengkulakuapp',
    storageBucket: 'tengkulakuapp.appspot.com',
    iosBundleId: 'com.example.projectTengkulakuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ohUxvduWEXx0ln6QJmZVxpGAh27mM50',
    appId: '1:589729199634:ios:252c3088a5a1c190d08acb',
    messagingSenderId: '589729199634',
    projectId: 'tengkulakuapp',
    storageBucket: 'tengkulakuapp.appspot.com',
    iosBundleId: 'com.example.projectTengkulakuApp.RunnerTests',
  );
}
