// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVPUb3m6H988pTFt177DtTCkJWy9iemrs',
    appId: '1:180241043532:web:8aadb2f1d4e75bd612a4e9',
    messagingSenderId: '180241043532',
    projectId: 'fir-flutter-25e66',
    authDomain: 'fir-flutter-25e66.firebaseapp.com',
    databaseURL: 'https://fir-flutter-25e66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-25e66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQl8M_h4RgP-uxxPa3iE2nbo56OHx75jI',
    appId: '1:180241043532:android:4ab5d9f2b00cf34e12a4e9',
    messagingSenderId: '180241043532',
    projectId: 'fir-flutter-25e66',
    databaseURL: 'https://fir-flutter-25e66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-25e66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnfkP7NpRUMPr7OxzZUOHYjFUEcVPRL8',
    appId: '1:180241043532:ios:49c499f529f9383312a4e9',
    messagingSenderId: '180241043532',
    projectId: 'fir-flutter-25e66',
    databaseURL: 'https://fir-flutter-25e66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-25e66.appspot.com',
    iosBundleId: 'com.example.projectTengkulakuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWnfkP7NpRUMPr7OxzZUOHYjFUEcVPRL8',
    appId: '1:180241043532:ios:06507a1fe34b16ec12a4e9',
    messagingSenderId: '180241043532',
    projectId: 'fir-flutter-25e66',
    databaseURL: 'https://fir-flutter-25e66-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-25e66.appspot.com',
    iosBundleId: 'com.example.projectTengkulakuApp.RunnerTests',
  );
}
